# Generated by Django 3.2.9 on 2021-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cartitems_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
    ]
